(()=>{
'use strict';
const d=document;const clamp=(v,a=0,b=1)=>Math.min(b,Math.max(a,v));const lerp=(a,b,t)=>a+(b-a)*t;
const header=d.querySelector('[data-header]');const menu=d.querySelector('.menu-toggle');const nav=d.querySelector('.main-nav');const pageBar=d.querySelector('[data-page-progress]');
function updateHeader(){header?.classList.toggle('is-scrolled',scrollY>28);const max=Math.max(1,d.documentElement.scrollHeight-innerHeight);if(pageBar)pageBar.style.width=`${scrollY/max*100}%`}updateHeader();addEventListener('scroll',updateHeader,{passive:true});
menu?.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));nav?.classList.toggle('is-open',open)});nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{menu?.setAttribute('aria-expanded','false');nav?.classList.remove('is-open')}));
const reveal=[...d.querySelectorAll('.reveal')];if('IntersectionObserver'in window){const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');io.unobserve(e.target)}}),{threshold:.12,rootMargin:'0px 0px -8%'});reveal.forEach(el=>io.observe(el))}else reveal.forEach(el=>el.classList.add('is-visible'));
const hero=d.querySelector('[data-hero]');const robot=d.querySelector('[data-robot]');const floats=[...d.querySelectorAll('[data-float]')];let px=0,py=0,tx=0,ty=0;const coarse=matchMedia('(pointer:coarse)').matches;
if(!coarse)addEventListener('pointermove',e=>{tx=(e.clientX/innerWidth-.5)*2;ty=(e.clientY/innerHeight-.5)*2},{passive:true});
function animateHero(){px=lerp(px,tx,.06);py=lerp(py,ty,.06);if(robot){robot.style.setProperty('--rx',`${(-py*4.5).toFixed(2)}deg`);robot.style.setProperty('--ry',`${(px*6).toFixed(2)}deg`)}floats.forEach((el,i)=>el.style.transform=`translate3d(${(px*(i?8:-10)).toFixed(1)}px,${(py*(i?6:-8)).toFixed(1)}px,${i?40:70}px)`);requestAnimationFrame(animateHero)}animateHero();
const scenes=[...d.querySelectorAll('[data-project-scene]')];let ticking=false;function updateScenes(){scenes.forEach(scene=>{const sticky=scene.querySelector('.project-visual');if(!sticky)return;const r=scene.getBoundingClientRect();const range=Math.max(1,r.height-innerHeight);const p=clamp(-r.top/range);sticky.style.setProperty('--scene-progress',p.toFixed(4));const desktop=sticky.querySelector('.device--desktop');const float=sticky.querySelector('.device--float,.device--phone');if(desktop)desktop.style.transform=`rotateY(${lerp(-12,2,p)}deg) rotateX(${lerp(5,0,p)}deg) translate3d(0,${lerp(30,-18,p)}px,${lerp(0,65,p)}px)`;if(float)float.style.transform=`rotateY(${lerp(18,-3,p)}deg) rotateX(${lerp(-5,0,p)}deg) translate3d(0,${lerp(36,-12,p)}px,${lerp(90,135,p)}px)`});ticking=false}addEventListener('scroll',()=>{if(!ticking){requestAnimationFrame(updateScenes);ticking=true}},{passive:true});updateScenes();
const tiltTargets=[...d.querySelectorAll('[data-project-tilt]')];if(!coarse)tiltTargets.forEach(el=>{el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect();const x=(e.clientX-r.left)/r.width-.5;const y=(e.clientY-r.top)/r.height-.5;el.style.transform=`rotateX(${(-y*2.6).toFixed(2)}deg) rotateY(${(x*3.4).toFixed(2)}deg)`});el.addEventListener('pointerleave',()=>el.style.transform='')});
const canvas=d.querySelector('[data-ambient]');if(canvas){const ctx=canvas.getContext('2d',{alpha:true});let dots=[];function resize(){const ratio=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(canvas.clientWidth*ratio);canvas.height=Math.round(canvas.clientHeight*ratio);ctx.setTransform(ratio,0,0,ratio,0,0);dots=Array.from({length:Math.max(24,Math.floor(canvas.clientWidth/48))},()=>({x:Math.random()*canvas.clientWidth,y:Math.random()*canvas.clientHeight,r:.6+Math.random()*1.5,v:.08+Math.random()*.18,a:.08+Math.random()*.16}))}resize();addEventListener('resize',resize,{passive:true});function draw(){ctx.clearRect(0,0,canvas.clientWidth,canvas.clientHeight);for(const q of dots){q.y-=q.v;if(q.y<-10){q.y=canvas.clientHeight+10;q.x=Math.random()*canvas.clientWidth}ctx.beginPath();ctx.arc(q.x,q.y,q.r,0,Math.PI*2);ctx.fillStyle=`rgba(41,151,255,${q.a})`;ctx.fill()}requestAnimationFrame(draw)}if(!matchMedia('(prefers-reduced-motion:reduce)').matches)draw()}
const data={suite:{title:'NCR Suite',lead:'Une plateforme modulaire conçue pour centraliser la gestion, les documents et les parcours métier.',challenge:'Réunir plusieurs besoins métiers dans une expérience unique sans rendre l’outil complexe.',approach:'Créer une architecture modulaire, des parcours cohérents et un système visuel commun.',value:'Un produit évolutif qui réduit la dispersion et facilite le pilotage quotidien.',tags:['SaaS','PWA','Dashboard','Automatisations','Responsive'],images:['assets/portfolio/ncr-suite-dashboard-real.png','assets/portfolio/ncr-suite-login-real.png']},sentinelle:{title:'Sentinelle Pro',lead:'Une PWA opérationnelle pensée pour connecter le QG et les agents de terrain.',challenge:'Faire remonter rapidement les informations utiles dans un contexte où chaque seconde compte.',approach:'Prioriser la lisibilité, l’action et l’usage mobile avec une interface dédiée aux réalités du terrain.',value:'Une vision plus claire des missions, alertes et événements opérationnels.',tags:['PWA','Sécurité privée','Cartographie','Mobile','Temps réel'],images:['assets/portfolio/sentinelle-dashboard-real.png','assets/portfolio/sentinelle-menu-real.png']},sst:{title:'Application SST',lead:'Une application mobile de révision et d’entraînement dédiée aux contenus SST.',challenge:'Rendre les contenus de formation rapides à consulter et faciles à mémoriser depuis un smartphone.',approach:'Découper les notions en modules courts, fiches et quiz avec une navigation directe.',value:'Une expérience mobile simple qui accompagne la préparation et la révision.',tags:['Mobile-first','Formation','Quiz','PWA','UX pédagogique'],images:['assets/portfolio/sst-home.webp','assets/portfolio/sst-modules.webp','assets/portfolio/sst-quiz.webp']},azzera:{title:'Sites Azzera',lead:'Un écosystème de sites vitrines cohérent, avec une identité propre à chaque activité.',challenge:'Différencier trois positionnements tout en conservant une véritable unité de groupe.',approach:'Définir une structure commune puis adapter les codes visuels, le ton et la promesse de chaque entité.',value:'Des univers lisibles, crédibles et immédiatement identifiables.',tags:['Sites vitrines','Direction artistique','Responsive','SEO','Identité de marque'],images:['assets/portfolio/azzera-invest-real.png','assets/portfolio/azzera-services-real.png','assets/portfolio/azzera-academy-real.png']}};
const dialog=d.querySelector('[data-project-dialog]');const close=d.querySelector('[data-close-dialog]');function openProject(key){const item=data[key];if(!dialog||!item)return;dialog.querySelector('[data-dialog-title]').textContent=item.title;dialog.querySelector('[data-dialog-lead]').textContent=item.lead;dialog.querySelector('[data-dialog-challenge]').textContent=item.challenge;dialog.querySelector('[data-dialog-approach]').textContent=item.approach;dialog.querySelector('[data-dialog-value]').textContent=item.value;dialog.querySelector('[data-dialog-tags]').innerHTML=item.tags.map(t=>`<span>${t}</span>`).join('');dialog.querySelector('[data-dialog-gallery]').innerHTML=item.images.map(src=>`<img src="${src}" alt="Aperçu du projet ${item.title}">`).join('');dialog.showModal();d.body.classList.add('dialog-open')}d.querySelectorAll('[data-open-project]').forEach(btn=>btn.addEventListener('click',()=>openProject(btn.dataset.openProject)));close?.addEventListener('click',()=>dialog.close());dialog?.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});dialog?.addEventListener('close',()=>d.body.classList.remove('dialog-open'));addEventListener('keydown',e=>{if(e.key==='Escape'&&dialog?.open)dialog.close()});
})();
