(()=>{'use strict';
const d=document,w=window;const clamp=(v,a=0,b=1)=>Math.min(b,Math.max(a,v));const lerp=(a,b,t)=>a+(b-a)*t;const smooth=t=>t*t*(3-2*t);const coarse=matchMedia('(pointer:coarse)').matches;

/* Header / global progress */
const header=d.querySelector('[data-header]'),pageBar=d.querySelector('[data-page-progress]'),menu=d.querySelector('.menu-toggle'),nav=d.querySelector('.main-nav');
let globalRAF=0;function onGlobalScroll(){if(globalRAF)return;globalRAF=requestAnimationFrame(()=>{globalRAF=0;header?.classList.toggle('is-scrolled',scrollY>28);const max=Math.max(1,d.documentElement.scrollHeight-innerHeight);if(pageBar)pageBar.style.width=`${clamp(scrollY/max)*100}%`;updateStack();})}addEventListener('scroll',onGlobalScroll,{passive:true});addEventListener('resize',onGlobalScroll,{passive:true});onGlobalScroll();
menu?.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));nav?.classList.toggle('is-open',open)});nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{menu?.setAttribute('aria-expanded','false');nav?.classList.remove('is-open')}));

/* Sparse starfield, no render loop */
const stars=d.querySelector('[data-stars]');function seeded(i){const x=Math.sin(i*981.31+17.77)*43758.5453;return x-Math.floor(x)}if(stars){const frag=d.createDocumentFragment();for(let i=0;i<58;i++){const s=d.createElement('i');s.className='star';s.style.left=`${(seeded(i+13)*100).toFixed(2)}%`;s.style.top=`${(seeded(i+71)*100).toFixed(2)}%`;s.style.setProperty('--twinkle',`${(4+seeded(i+111)*6).toFixed(2)}s`);s.style.setProperty('--delay',`${(-seeded(i+171)*9).toFixed(2)}s`);frag.appendChild(s)}stars.appendChild(frag)}

/* Reveal */
const reveals=[...d.querySelectorAll('.reveal')];if('IntersectionObserver'in w){const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');io.unobserve(e.target)}}),{threshold:.08,rootMargin:'0px 0px -5%'});reveals.forEach(el=>{if(!el.classList.contains('is-visible'))io.observe(el)})}else reveals.forEach(el=>el.classList.add('is-visible'));

/* Hero robot: premium restrained motion */
const heroObject=d.querySelector('[data-hero-object]'),heroRobot=d.querySelector('[data-hero-robot]');if(heroObject&&heroRobot&&!coarse){let raf=0,tx=0,ty=0,cx=0,cy=0;const draw=()=>{raf=0;cx+=(tx-cx)*.08;cy+=(ty-cy)*.08;heroRobot.style.setProperty('--ry',`${(cx*10).toFixed(2)}deg`);heroRobot.style.setProperty('--rx',`${(-cy*7).toFixed(2)}deg`);if(Math.abs(tx-cx)>.005||Math.abs(ty-cy)>.005)raf=requestAnimationFrame(draw)};heroObject.addEventListener('pointermove',e=>{const r=heroObject.getBoundingClientRect();tx=clamp((e.clientX-r.left)/r.width*2-1,-1,1);ty=clamp((e.clientY-r.top)/r.height*2-1,-1,1);if(!raf)raf=requestAnimationFrame(draw)},{passive:true});heroObject.addEventListener('pointerleave',()=>{tx=0;ty=0;if(!raf)raf=requestAnimationFrame(draw)},{passive:true})}

/* Magnetic stack */
const stack=d.querySelector('[data-project-stack]'),stage=d.querySelector('[data-stack-stage]'),cards=[...d.querySelectorAll('[data-stack-card]')],rail=[...d.querySelectorAll('[data-stack-jump]')],stackBar=d.querySelector('[data-stack-progress]'),stackLabel=d.querySelector('[data-stack-label]');let active=-1,lastLanding=-1;
const labels=['01 / NCR Suite','02 / Sentinelle Pro','03 / Application SST','04 / Sites Azzera'];
function stackMetrics(){if(!stack)return null;const rect=stack.getBoundingClientRect();const range=Math.max(1,stack.offsetHeight-innerHeight);return{p:clamp(-rect.top/range),rect,range}}
function updateStack(){if(!stack||innerWidth<=900)return;const m=stackMetrics();if(!m)return;const p=m.p;if(stackBar)stackBar.style.width=`${p*100}%`;const n=cards.length;const scaled=p*(n+.55);const current=clamp(Math.floor(scaled),0,n-1);active=current;if(stackLabel)stackLabel.textContent=labels[current];rail.forEach((b,i)=>b.classList.toggle('is-active',i===current));if(stage)stage.style.setProperty('--magnet',(0.18+Math.sin(p*Math.PI*n)**2*.5).toFixed(3));
  cards.forEach((card,i)=>{
    const local=scaled-i;let x=0,y=0,z=0,rx=0,ry=0,rz=0,s=.96,o=0;
    if(local<0){const t=clamp(1+local);const e=smooth(t);x=lerp(180,0,e);y=lerp(innerHeight*.62,0,e);z=lerp(-700,0,e);rx=lerp(16,0,e);ry=lerp(-22,0,e);rz=lerp(8,0,e);s=lerp(.72,1,e);o=clamp(t*1.3)}
    else if(local<=1){const e=smooth(clamp(local));x=lerp(120,0,e);y=lerp(innerHeight*.46,0,e);z=lerp(-520,0,e);rx=lerp(12,0,e);ry=lerp(-16,0,e);rz=lerp(6,0,e);s=lerp(.78,1,e);o=clamp(.18+e*1.1)}
    else{const behind=Math.min(local-1,3);x=-behind*10;y=-behind*15;z=-behind*82;rx=behind*.45;ry=behind*-1.15;rz=(i%2?1:-1)*behind*.65;s=1-behind*.032;o=Math.max(.25,1-behind*.22)}
    card.style.setProperty('--card-x',`${x.toFixed(2)}px`);card.style.setProperty('--card-y',`${y.toFixed(2)}px`);card.style.setProperty('--card-z',`${z.toFixed(2)}px`);card.style.setProperty('--card-rx',`${rx.toFixed(2)}deg`);card.style.setProperty('--card-ry',`${ry.toFixed(2)}deg`);card.style.setProperty('--card-rz',`${rz.toFixed(2)}deg`);card.style.setProperty('--card-scale',s.toFixed(4));card.style.setProperty('--card-opacity',o.toFixed(3));card.style.zIndex=String(20+i);card.classList.toggle('is-active',i===current&&local>.72);const landing=i===current&&local>.76&&local<.9;if(landing&&lastLanding!==i){card.classList.remove('is-landing');void card.offsetWidth;card.classList.add('is-landing');lastLanding=i}
  })
}
rail.forEach((b,i)=>b.addEventListener('click',()=>{if(!stack||innerWidth<=900)return;const top=scrollY+stack.getBoundingClientRect().top;const range=Math.max(1,stack.offsetHeight-innerHeight);const target=(i+.82)/(cards.length+.55);scrollTo({top:top+target*range,behavior:'smooth'})}));

/* Azzera horizontal carousel */
const az=d.querySelector('[data-azzera-carousel]');if(az){const slides=[...az.querySelectorAll('[data-azzera-slide]')],dots=[...d.querySelectorAll('.azzera-dots i')],prev=d.querySelector('[data-azzera-prev]'),next=d.querySelector('[data-azzera-next]');let idx=0,raf=0;function nearest(){const center=az.scrollLeft+az.clientWidth/2;let best=0,dist=Infinity;slides.forEach((s,i)=>{const dlt=Math.abs(s.offsetLeft+s.offsetWidth/2-center);if(dlt<dist){dist=dlt;best=i}});return best}function render(){raf=0;const center=az.scrollLeft+az.clientWidth/2;slides.forEach(s=>{const delta=(s.offsetLeft+s.offsetWidth/2-center)/Math.max(1,az.clientWidth);s.style.transform=`rotateY(${clamp(-delta*9,-8,8).toFixed(2)}deg) translateY(${(Math.abs(delta)*8).toFixed(1)}px) scale(${(1-Math.min(.035,Math.abs(delta)*.028)).toFixed(3)})`;s.style.opacity=(1-Math.min(.25,Math.abs(delta)*.18)).toFixed(2)});dots.forEach((x,i)=>x.classList.toggle('is-active',i===idx));if(prev)prev.disabled=idx===0;if(next)next.disabled=idx===slides.length-1}function queue(){if(!raf)raf=requestAnimationFrame(render)}function go(i){idx=clamp(i,0,slides.length-1);const s=slides[idx];if(s)az.scrollTo({left:Math.max(0,s.offsetLeft-(az.clientWidth-s.offsetWidth)/2),behavior:'smooth'});queue()}az.addEventListener('scroll',()=>{idx=nearest();queue()},{passive:true});az.addEventListener('keydown',e=>{if(e.key==='ArrowRight'){e.preventDefault();go(idx+1)}if(e.key==='ArrowLeft'){e.preventDefault();go(idx-1)}});prev?.addEventListener('click',()=>go(idx-1));next?.addEventListener('click',()=>go(idx+1));addEventListener('resize',()=>go(idx),{passive:true});render()}

/* Dialog data */
const projectData={suite:{title:'NCR Suite',lead:'Une plateforme modulaire conçue pour centraliser la gestion, les documents et les parcours métier.',challenge:'Réunir plusieurs besoins métiers dans une expérience unique sans rendre l’outil complexe.',approach:'Créer une architecture modulaire, des parcours cohérents et un système visuel commun.',value:'Un produit évolutif qui réduit la dispersion et facilite le pilotage quotidien.',tags:['SaaS','PWA','Dashboard','Automatisations','Responsive'],images:['assets/portfolio/ncr-suite-dashboard-real.png','assets/portfolio/ncr-suite-login-real.png']},sentinelle:{title:'Sentinelle Pro',lead:'Une PWA opérationnelle pensée pour connecter le QG et les agents de terrain.',challenge:'Faire remonter rapidement les informations utiles dans un contexte où chaque seconde compte.',approach:'Prioriser la lisibilité, l’action et l’usage mobile avec une interface dédiée aux réalités du terrain.',value:'Une vision plus claire des missions, alertes et événements opérationnels.',tags:['PWA','Sécurité privée','Cartographie','Mobile','Temps réel'],images:['assets/portfolio/sentinelle-dashboard-real.png','assets/portfolio/sentinelle-menu-real.png']},sst:{title:'Application SST',lead:'Une application mobile de révision et d’entraînement dédiée aux contenus SST.',challenge:'Rendre les contenus rapides à consulter et faciles à mémoriser depuis un smartphone.',approach:'Découper les notions en modules courts, fiches et quiz avec une navigation directe.',value:'Une expérience mobile simple qui accompagne la préparation et la révision.',tags:['Mobile-first','Formation','Quiz','PWA','UX pédagogique'],images:['assets/portfolio/sst-home.webp','assets/portfolio/sst-modules.webp','assets/portfolio/sst-quiz.webp']},azzera:{title:'Sites Azzera',lead:'Un écosystème de sites vitrines cohérent, avec une identité propre à chaque activité.',challenge:'Différencier trois positionnements tout en conservant une véritable unité de groupe.',approach:'Définir une structure commune puis adapter les codes visuels, le ton et la promesse de chaque entité.',value:'Des univers lisibles, crédibles et immédiatement identifiables.',tags:['Sites vitrines','Direction artistique','Responsive','SEO','Identité de marque'],images:['assets/portfolio/azzera-invest-real.png','assets/portfolio/azzera-services-real.png','assets/portfolio/azzera-academy-real.png']}};
const dialog=d.querySelector('[data-project-dialog]');function openProject(key){const p=projectData[key];if(!dialog||!p)return;dialog.querySelector('[data-dialog-title]').textContent=p.title;dialog.querySelector('[data-dialog-lead]').textContent=p.lead;dialog.querySelector('[data-dialog-challenge]').textContent=p.challenge;dialog.querySelector('[data-dialog-approach]').textContent=p.approach;dialog.querySelector('[data-dialog-value]').textContent=p.value;dialog.querySelector('[data-dialog-tags]').innerHTML=p.tags.map(t=>`<span>${t}</span>`).join('');dialog.querySelector('[data-dialog-gallery]').innerHTML=p.images.map(src=>`<img src="${src}" alt="Aperçu du projet ${p.title}">`).join('');dialog.showModal();d.body.classList.add('dialog-open')}d.querySelectorAll('[data-open-project]').forEach(b=>b.addEventListener('click',()=>openProject(b.dataset.openProject)));d.querySelector('[data-close-dialog]')?.addEventListener('click',()=>dialog?.close());dialog?.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});dialog?.addEventListener('close',()=>d.body.classList.remove('dialog-open'));

updateStack();
})();
