(()=>{
'use strict';
const d=document,w=window;
const clamp=(v,a=0,b=1)=>Math.min(b,Math.max(a,v));
const coarse=matchMedia('(pointer:coarse)').matches;

/* Header, progression, mobile nav */
const header=d.querySelector('[data-header]'),bar=d.querySelector('[data-page-progress]'),menu=d.querySelector('.menu-toggle'),nav=d.querySelector('.main-nav');
let scrollTick=0;
function scheduleScroll(){if(scrollTick)return;scrollTick=requestAnimationFrame(()=>{scrollTick=0;const max=Math.max(1,d.documentElement.scrollHeight-innerHeight);header?.classList.toggle('is-scrolled',scrollY>28);if(bar)bar.style.width=`${clamp(scrollY/max)*100}%`;updateCases();updateHeroScroll()})}
addEventListener('scroll',scheduleScroll,{passive:true});addEventListener('resize',scheduleScroll,{passive:true});scheduleScroll();
menu?.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));nav?.classList.toggle('is-open',open)});nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{menu?.setAttribute('aria-expanded','false');nav?.classList.remove('is-open')}));

/* Ambient stars + shooting stars: lightweight DOM/CSS, no render loop */
const stars=d.querySelector('[data-stars]'),meteors=d.querySelector('[data-meteors]'),field=d.querySelector('[data-space-field]');
function seeded(i){const x=Math.sin(i*999.71+13.37)*43758.5453;return x-Math.floor(x)}
if(stars){const count=52;const frag=d.createDocumentFragment();for(let i=0;i<count;i++){const s=d.createElement('i');const r=seeded(i);s.className='star'+(i%7===0?' star--bright':i%3===0?' star--ink':'');s.style.left=`${(seeded(i+41)*100).toFixed(2)}%`;s.style.top=`${(seeded(i+83)*100).toFixed(2)}%`;s.style.setProperty('--twinkle',`${(3.8+seeded(i+91)*5.2).toFixed(2)}s`);s.style.setProperty('--delay',`${(-seeded(i+111)*7).toFixed(2)}s`);s.style.opacity=(.15+r*.5).toFixed(2);frag.appendChild(s)}stars.appendChild(frag)}
if(meteors){const configs=[['7%','8%','11.5s','-2.1s'],['62%','18%','14s','-7.4s'],['18%','42%','16s','-12s'],['71%','55%','12.5s','-4.8s'],['36%','77%','18s','-13.5s']];configs.forEach(c=>{const m=d.createElement('i');m.className='meteor';m.style.left=c[0];m.style.top=c[1];m.style.setProperty('--duration',c[2]);m.style.setProperty('--delay',c[3]);meteors.appendChild(m)})}
if(field&&!coarse){let raf=0,tx=0,ty=0,cx=0,cy=0;const draw=()=>{raf=0;cx+=(tx-cx)*.08;cy+=(ty-cy)*.08;field.style.setProperty('--space-x',`${cx.toFixed(2)}px`);field.style.setProperty('--space-y',`${cy.toFixed(2)}px`);stars&&(stars.style.transform=`translate3d(${cx}px,${cy}px,0)`);if(Math.abs(tx-cx)>.05||Math.abs(ty-cy)>.05)raf=requestAnimationFrame(draw)};addEventListener('pointermove',e=>{tx=(e.clientX/innerWidth-.5)*-10;ty=(e.clientY/innerHeight-.5)*-8;if(!raf)raf=requestAnimationFrame(draw)},{passive:true})}

/* reveal only */
const reveals=[...d.querySelectorAll('.reveal')];if('IntersectionObserver'in w){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');io.unobserve(e.target)}}),{threshold:.11,rootMargin:'0px 0px -6%'});reveals.forEach(el=>{if(!el.classList.contains('is-visible'))io.observe(el)})}else reveals.forEach(el=>el.classList.add('is-visible'));

/* Hero object tilt */
const heroObject=d.querySelector('[data-hero-object]'),heroRobot=d.querySelector('[data-hero-robot]');
if(heroObject&&heroRobot&&!coarse){let raf=0,tx=0,ty=0,cx=0,cy=0;const draw=()=>{raf=0;cx+=(tx-cx)*.1;cy+=(ty-cy)*.1;heroRobot.style.setProperty('--ry',`${(cx*8).toFixed(2)}deg`);heroRobot.style.setProperty('--rx',`${(-cy*6).toFixed(2)}deg`);if(Math.abs(tx-cx)>.01||Math.abs(ty-cy)>.01)raf=requestAnimationFrame(draw)};heroObject.addEventListener('pointermove',e=>{const r=heroObject.getBoundingClientRect();tx=clamp((e.clientX-r.left)/r.width*2-1,-1,1);ty=clamp((e.clientY-r.top)/r.height*2-1,-1,1);if(!raf)raf=requestAnimationFrame(draw)},{passive:true});heroObject.addEventListener('pointerleave',()=>{tx=0;ty=0;if(!raf)raf=requestAnimationFrame(draw)},{passive:true})}
function updateHeroScroll(){if(!heroRobot)return;const p=clamp(scrollY/Math.max(innerHeight,1),0,1);heroRobot.style.translate=`0 ${(-p*14).toFixed(2)}px`;heroRobot.style.filter=`saturate(${(1-p*.08).toFixed(3)})`}

/* Scene parallax only while in/near viewport */
const cases=[...d.querySelectorAll('[data-case]')].map(el=>({el,stage:el.querySelector('[data-case-stage]')}));
function updateCases(){const vh=innerHeight;cases.forEach(({el,stage})=>{if(!stage)return;const r=el.getBoundingClientRect();if(r.bottom<-vh*.2||r.top>vh*1.2)return;const center=r.top+r.height/2;const delta=clamp((center-vh/2)/(vh*1.2),-1,1);stage.style.transform=`translate3d(0,${(-delta*12).toFixed(2)}px,0) rotateX(${(delta*1.4).toFixed(2)}deg)`})}

/* Azzera carousel */
const az=d.querySelector('[data-azzera-carousel]');if(az){const slides=[...az.querySelectorAll('[data-azzera-slide]')],dots=[...d.querySelectorAll('.azzera-dots i')],prev=d.querySelector('[data-azzera-prev]'),next=d.querySelector('[data-azzera-next]');let index=0,af=0;function nearest(){const c=az.scrollLeft+az.clientWidth/2;let best=0,dist=Infinity;slides.forEach((s,i)=>{const x=Math.abs(s.offsetLeft+s.offsetWidth/2-c);if(x<dist){dist=x;best=i}});return best}function render(){af=0;const c=az.scrollLeft+az.clientWidth/2;slides.forEach((s,i)=>{const delta=(s.offsetLeft+s.offsetWidth/2-c)/Math.max(1,az.clientWidth);const a=Math.min(1.25,Math.abs(delta));s.style.transform=`translate3d(0,${(a*12).toFixed(1)}px,${((1-a)*50).toFixed(1)}px) rotateY(${clamp(-delta*8,-8,8).toFixed(2)}deg) scale(${(1-Math.min(.045,a*.04)).toFixed(3)})`;s.style.opacity=(1-Math.min(.22,a*.17)).toFixed(2)});dots.forEach((q,i)=>q.classList.toggle('is-active',i===index));if(prev)prev.disabled=index===0;if(next)next.disabled=index===slides.length-1}function queue(){if(!af)af=requestAnimationFrame(render)}function go(i){index=clamp(i,0,slides.length-1);const s=slides[index];if(s)az.scrollTo({left:Math.max(0,s.offsetLeft-(az.clientWidth-s.offsetWidth)/2),behavior:'smooth'});queue()}az.addEventListener('scroll',()=>{index=nearest();queue()},{passive:true});az.addEventListener('keydown',e=>{if(e.key==='ArrowRight'){e.preventDefault();go(index+1)}if(e.key==='ArrowLeft'){e.preventDefault();go(index-1)}});prev?.addEventListener('click',()=>go(index-1));next?.addEventListener('click',()=>go(index+1));addEventListener('resize',()=>go(index),{passive:true});render()}

/* Project dialogs */
const projectData={
  suite:{title:'NCR Suite',lead:'Une plateforme modulaire conçue pour centraliser la gestion, les documents et les parcours métier.',challenge:'Réunir plusieurs besoins métiers dans une expérience unique sans rendre l’outil complexe.',approach:'Créer une architecture modulaire, des parcours cohérents et un système visuel commun.',value:'Un produit évolutif qui réduit la dispersion et facilite le pilotage quotidien.',tags:['SaaS','PWA','Dashboard','Automatisations','Responsive'],images:['assets/portfolio/ncr-suite-dashboard-real.png','assets/portfolio/ncr-suite-login-real.png']},
  sentinelle:{title:'Sentinelle Pro',lead:'Une PWA opérationnelle pensée pour connecter le QG et les agents de terrain.',challenge:'Faire remonter rapidement les informations utiles dans un contexte où chaque seconde compte.',approach:'Prioriser la lisibilité, l’action et l’usage mobile avec une interface dédiée aux réalités du terrain.',value:'Une vision plus claire des missions, alertes et événements opérationnels.',tags:['PWA','Sécurité privée','Cartographie','Mobile','Temps réel'],images:['assets/portfolio/sentinelle-dashboard-real.png','assets/portfolio/sentinelle-menu-real.png']},
  sst:{title:'Application SST',lead:'Une application mobile de révision et d’entraînement dédiée aux contenus SST.',challenge:'Rendre les contenus de formation rapides à consulter et faciles à mémoriser depuis un smartphone.',approach:'Découper les notions en modules courts, fiches et quiz avec une navigation directe.',value:'Une expérience mobile simple qui accompagne la préparation et la révision.',tags:['Mobile-first','Formation','Quiz','PWA','UX pédagogique'],images:['assets/portfolio/sst-home.webp','assets/portfolio/sst-modules.webp','assets/portfolio/sst-quiz.webp']},
  azzera:{title:'Sites Azzera',lead:'Un écosystème de sites vitrines cohérent, avec une identité propre à chaque activité.',challenge:'Différencier trois positionnements tout en conservant une véritable unité de groupe.',approach:'Définir une structure commune puis adapter les codes visuels, le ton et la promesse de chaque entité.',value:'Des univers lisibles, crédibles et immédiatement identifiables.',tags:['Sites vitrines','Direction artistique','Responsive','SEO','Identité de marque'],images:['assets/portfolio/azzera-invest-real.png','assets/portfolio/azzera-services-real.png','assets/portfolio/azzera-academy-real.png']}
};
const dialog=d.querySelector('[data-project-dialog]');function openProject(key){const p=projectData[key];if(!dialog||!p)return;dialog.querySelector('[data-dialog-title]').textContent=p.title;dialog.querySelector('[data-dialog-lead]').textContent=p.lead;dialog.querySelector('[data-dialog-challenge]').textContent=p.challenge;dialog.querySelector('[data-dialog-approach]').textContent=p.approach;dialog.querySelector('[data-dialog-value]').textContent=p.value;dialog.querySelector('[data-dialog-tags]').innerHTML=p.tags.map(t=>`<span>${t}</span>`).join('');dialog.querySelector('[data-dialog-gallery]').innerHTML=p.images.map(src=>`<img src="${src}" alt="Aperçu du projet ${p.title}">`).join('');dialog.showModal();d.body.classList.add('dialog-open')}d.querySelectorAll('[data-open-project]').forEach(b=>b.addEventListener('click',()=>openProject(b.dataset.openProject)));d.querySelector('[data-close-dialog]')?.addEventListener('click',()=>dialog?.close());dialog?.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});dialog?.addEventListener('close',()=>d.body.classList.remove('dialog-open'));
})();
